# Generated by Django 4.2.6 on 2023-10-17 00:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_remove_test_lesson_test_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
