# Generated by Django 4.2.6 on 2023-10-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'Lesson'},
        ),
    ]
