# Generated by Django 4.2.6 on 2023-10-21 08:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
