# Generated by Django 4.2.6 on 2023-10-21 09:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_alter_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255),
        ),
    ]
