# Generated by Django 4.2.6 on 2023-10-21 09:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_alter_test_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
