# Generated by Django 4.2.6 on 2023-10-22 14:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0043_remove_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
