# Generated by Django 4.2.6 on 2023-10-22 14:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_alter_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
