# Generated by Django 4.2.6 on 2023-10-29 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0053_alter_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
