# Generated by Django 4.2.6 on 2023-11-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_remove_test_end_time_remove_test_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
