# Generated by Django 4.2.6 on 2023-11-02 01:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0058_alter_question_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
