# Generated by Django 4.2.6 on 2023-11-02 01:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0059_remove_question_description_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
