# Generated by Django 4.2.6 on 2023-11-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0066_testhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestHistory',
        ),
    ]
